version: "3.9"

services:
  redis:
    image: redis:7

  api:
    build: ../
    command: node api/server.js
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  worker:
    build:
      context: ../
      dockerfile: docker/Dockerfile.worker
    environment:
      - REDIS_URL=redis://redis:6379
    deploy:
      replicas: 10
    depends_on:
      - redis
